# Date created: 04/03/2024
# Last modified: 13/09/2024
# Author: Gustavo V. Barroso
# This script collects tables generated by bgs_pi.R and builds linear models
# of the form pi ~ u + B
# for a given model / replicate at different scales (bin_sizes 1kb, 10kb, 100kb) 
# and then writes a table with the R^2 explained by each independent variable

#!/usr/bin/env Rscript
args=commandArgs(trailingOnly=T)

prefix = "model"
if(length(args==1)) {
  prefix = args[1]
}

pdf(NULL) # to suppress creation of Rplots.pdf

suppressMessages({
  library(R.utils)
  library(tidyverse)
  library(MASS)
  library(lmtest)
  library(nlme)
  library(car)
  library(data.table)
  library(interactions)
})

print(Sys.time())
cat("Fitting linear models pi ~ u + B...\n")

maps_1kb <- fread(paste(prefix, "_1kb.csv.gz", sep=""))
maps_10kb <- fread(paste(prefix, "_10kb.csv.gz", sep=""))
maps_100kb <- fread(paste(prefix, "_100kb.csv.gz", sep=""))
maps_1Mb <- fread(paste(prefix, "_1Mb.csv.gz", sep=""))

# tables for storing R^2 values from linear models (rows are bin sizes)
r2_tbl <- as.data.frame(matrix(ncol=3, nrow=4))
names(r2_tbl) <- c("u", "B", "B:u")
r2_tbl$scale <- c(1e+3, 1e+4, 1e+5, 1e+6)

# tables for storing estimates from linear models (rows are bin sizes)
coeff_tbl <- as.data.frame(matrix(ncol=3, nrow=4))
pval_tbl <- as.data.frame(matrix(ncol=3, nrow=4))
names(coeff_tbl) <- c("u", "B", "B:u")
names(pval_tbl) <- c("u", "B", "B:u")
coeff_tbl$scale <- c(1e+3, 1e+4, 1e+5, 1e+6)
pval_tbl$scale <- c(1e+3, 1e+4, 1e+5, 1e+6)

# VIFs
vif_tbl <- as.data.frame(matrix(ncol=2, nrow=4))
names(vif_tbl) <- c("u", "B")
vif_tbl$scale <- c(1e+3, 1e+4, 1e+5, 1e+6)

# standardizing variables to help interpretation of linear coefficients
tbl_1kb <- dplyr::select(maps_1kb, c(avg_mut, B, avg_pi))
std_1kb <- as.data.frame(apply(tbl_1kb, 2, function(x) (x-mean(x)) / sd(x)))
std_1kb$bin <- 1:nrow(std_1kb)

tbl_10kb <- dplyr::select(maps_10kb, c(avg_mut, B, avg_pi))
std_10kb <- as.data.frame(apply(tbl_10kb, 2, function(x) (x-mean(x)) / sd(x)))
std_10kb$bin <- 1:nrow(std_10kb)

tbl_100kb <- dplyr::select(maps_100kb, c(avg_mut, B, avg_pi))
std_100kb <- as.data.frame(apply(tbl_100kb, 2, function(x) (x-mean(x)) / sd(x)))
std_100kb$bin <- 1:nrow(std_100kb)

tbl_1Mb <- dplyr::select(maps_1Mb, c(avg_mut, B, avg_pi))
std_1Mb <- as.data.frame(apply(tbl_1Mb, 2, function(x) (x-mean(x)) / sd(x)))
std_1Mb$bin <- 1:nrow(std_1Mb)

# 1 kb
m_1kb <- lm(avg_pi ~ (B + avg_mut) ^ 2, std_1kb)
summary(m_1kb)
v1kb <- vif(m_1kb, type = 'predictor')

vif_tbl$B[1] <- v1kb$GVIF[1]
vif_tbl$u[1] <- v1kb$GVIF[2]

coeff_tbl$u[1] <- m_1kb$coefficients[3]
coeff_tbl$B[1] <- m_1kb$coefficients[2]
coeff_tbl$`B:u`[1] <- m_1kb$coefficients[4]

pval_tbl$u[1] <- summary(m_1kb)$coefficients[3,4]
pval_tbl$B[1] <- summary(m_1kb)$coefficients[2,4]
pval_tbl$`B:u`[1] <- summary(m_1kb)$coefficients[4,4]

anova.pi <- Anova(m_1kb)
apiss <- anova.pi$"Sum Sq"
anova.pi$VarExp <- apiss / sum(apiss)

r2_tbl$`B:u`[1] <- anova.pi$VarExp[3] * 100
r2_tbl$u[1] <- anova.pi$VarExp[2] * 100
r2_tbl$B[1] <- anova.pi$VarExp[1] * 100

# 10 kb
m_10kb <- lm(avg_pi ~ (B + avg_mut) ^ 2, std_10kb)
summary(m_10kb)
v10kb <- vif(m_10kb, type = 'predictor')

vif_tbl$B[2] <- v10kb$GVIF[1]
vif_tbl$u[2] <- v10kb$GVIF[2]

coeff_tbl$u[2] <- m_10kb$coefficients[3]
coeff_tbl$B[2] <- m_10kb$coefficients[2]
coeff_tbl$`B:u`[2] <- m_10kb$coefficients[4]

pval_tbl$u[2] <- summary(m_10kb)$coefficients[3,4]
pval_tbl$B[2] <- summary(m_10kb)$coefficients[2,4]
pval_tbl$`B:u`[2] <- summary(m_10kb)$coefficients[4,4]

anova.pi <- Anova(m_10kb)
apiss <- anova.pi$"Sum Sq"
anova.pi$VarExp <- apiss / sum(apiss)

r2_tbl$`B:u`[2] <- anova.pi$VarExp[3] * 100
r2_tbl$u[2] <- anova.pi$VarExp[2] * 100
r2_tbl$B[2] <- anova.pi$VarExp[1] * 100

# 100 kb
m_100kb <- lm(avg_pi ~ (B + avg_mut) ^ 2, std_100kb)
summary(m_100kb)
v100kb <- vif(m_100kb, type = 'predictor')

vif_tbl$B[3] <- v100kb$GVIF[1]
vif_tbl$u[3] <- v100kb$GVIF[2]

coeff_tbl$u[3] <- m_100kb$coefficients[3]
coeff_tbl$B[3] <- m_100kb$coefficients[2]
coeff_tbl$`B:u`[3] <- m_100kb$coefficients[4]

pval_tbl$u[3] <- summary(m_100kb)$coefficients[3,4]
pval_tbl$B[3] <- summary(m_100kb)$coefficients[2,4]
pval_tbl$`B:u`[3] <- summary(m_100kb)$coefficients[4,4]

anova.pi <- Anova(m_100kb)
apiss <- anova.pi$"Sum Sq"
anova.pi$VarExp <- apiss / sum(apiss)

r2_tbl$`B:u`[3] <- anova.pi$VarExp[3] * 100
r2_tbl$u[3] <- anova.pi$VarExp[2] * 100
r2_tbl$B[3] <- anova.pi$VarExp[1] * 100

# 1 Mb
m_1Mb <- lm(avg_pi ~ (B + avg_mut) ^ 2, data=std_1Mb)
summary(m_1Mb)
v1Mb <- vif(m_1Mb, type = 'predictor')

vif_tbl$B[4] <- v1Mb$GVIF[1]
vif_tbl$u[4] <- v1Mb$GVIF[2]

coeff_tbl$u[4] <- m_1Mb$coefficients[3]
coeff_tbl$B[4] <- m_1Mb$coefficients[2]
coeff_tbl$`B:u`[4] <- m_1Mb$coefficients[4]

pval_tbl$u[4] <- summary(m_1Mb)$coefficients[3,4]
pval_tbl$B[4] <- summary(m_1Mb)$coefficients[2,4]
pval_tbl$`B:u`[4] <- summary(m_1Mb)$coefficients[4,4]

anova.pi <- Anova(m_1Mb)
apiss <- anova.pi$"Sum Sq"
anova.pi$VarExp <- apiss / sum(apiss)

r2_tbl$`B:u`[4] <- anova.pi$VarExp[3] * 100
r2_tbl$u[4] <- anova.pi$VarExp[2] * 100
r2_tbl$B[4] <- anova.pi$VarExp[1] * 100

fwrite(coeff_tbl, paste(prefix, "_coeff_tbl.csv.gz", sep=""))
fwrite(pval_tbl, paste(prefix, "_pval_tbl.csv.gz", sep=""))
fwrite(r2_tbl, paste(prefix, "_r2_tbl.csv.gz", sep=""))
fwrite(vif_tbl, paste(prefix, "_vif_tbl.csv.gz", sep=""))

cat("bgs_lm.R is done!\n\n")
