# Date created: 04/03/2024
# Last modified: 21/08/2024
# Author: Gustavo V. Barroso
# Uses data generated by setup_models_2.Rmd to simulate chromosomal landscapes of
# mutation, recombination and elements, for which B-values and expectations of
# pi0 and pi can be computed using python scripts

#!/usr/bin/env Rscript
args=commandArgs(trailingOnly=T)

m <- as.numeric(args[1]) # index of focal model

pdf(NULL) # to suppress creation of Rplots.pdf

suppressMessages({
  library(R.utils)
  library(bigsnpr) # for seq_log()
  library(tidyverse)
  library(data.table)
  library(GenomicRanges)
  library(cowplot)
  library(scales)
})

# loads the main tables generated by setup_models_2.Rmd
models <- fread("../../models.csv")
cat(paste("Building random genomic landscapes under model", m, "\n"))

bin_size <- 1e+3 # "basal" scale, larger windows are built after
L <- models$L[m]
V <- L - models$exon_lengths[m] * models$num_exons[m]

## elements 
intergenic_lengths <- rgeom(n=models$num_exons[m], 
                            prob=models$num_exons[m]/V) 
while(sum(intergenic_lengths) < V) {
  intergenic_lengths <- c(intergenic_lengths, 
                          rgeom(n=1, prob=models$num_exons[m]/V))
}
if(sum(intergenic_lengths) > V) {
  intergenic_lengths <- intergenic_lengths[cumsum(intergenic_lengths) < V]
  intergenic_lengths <- c(intergenic_lengths, V - sum(intergenic_lengths))
}

elements <- suppressWarnings(c(rbind(intergenic_lengths, 
  rep(models$exon_lengths[m], models$num_exons[m]))))
elements <- suppressMessages(setDT(bind_cols(chr="chr1",
		                    dplyr::lag(cumsum(elements), n=1, default=0),
		                    dplyr::lag(cumsum(elements), n=0, default=0))))
names(elements) <- c("chr", "start", "end")
elements <- filter(elements, start < L)
elements$end[nrow(elements)] <- L
elements$selected <- as.integer(elements$end - elements$start == models$exon_lengths[m])

## rec map
rec_spans <- rgeom(n=ceiling(L/models$avg_rec_spans[m]),
 	                 prob=1/models$avg_rec_spans[m])
while(sum(rec_spans) < L) {
  rec_spans <- c(rec_spans, rgeom(n=1, prob=1/models$avg_rec_spans[m]))
}
if(sum(rec_spans) > L) {
  rec_spans <- rec_spans[cumsum(rec_spans) < L]
  rec_spans <- c(rec_spans, L - sum(rec_spans))
}
rec_spans <- rec_spans[rec_spans>0]

rmap <- suppressMessages(setDT(bind_cols(chr="chr1",
        		  dplyr::lag(cumsum(rec_spans), n=1, default=0),
		          dplyr::lag(cumsum(rec_spans), n=0, default=0))))  
names(rmap) <- c("chr", "start", "end")
rs <- rgamma(n=nrow(rmap),
             shape=models$shapes_rate_r[m],
             rate=models$shapes_rate_r[m])
rmap$r <- rs * models$mean_r[m]
fwrite(rmap, "rec_map.csv.gz")

mut_spans <- rgeom(n=ceiling(L/models$avg_mut_spans[m]),
            	     prob=1/models$avg_mut_spans[m])
while(sum(mut_spans) < L) {
  mut_spans <- c(mut_spans, rgeom(n=1, prob=1/models$avg_mut_spans[m]))
}
if(sum(mut_spans) > L) {
  mut_spans <- mut_spans[cumsum(mut_spans) < L]
  mut_spans <- c(mut_spans, L - sum(mut_spans))
}
mut_spans <- mut_spans[mut_spans>0]

mmap <- suppressMessages(setDT(bind_cols(chr="chr1",
         		  dplyr::lag(cumsum(mut_spans), n=1, default=0),
		          dplyr::lag(cumsum(mut_spans), n=0, default=0))))
names(mmap) <- c("chr", "start", "end")
mus <- rgamma(n=nrow(mmap),
            	shape=models$shapes_rate_u[m],
            	rate=models$shapes_rate_u[m])
mmap$u <- mus * models$mean_u[m]
fwrite(mmap, "mut_map.csv.gz")

# binning
bins <- rep(bin_size, floor(L / bin_size))
bins <- suppressMessages(bind_cols(chr="chr1",
                  dplyr::lag(cumsum(bins), n=1, default=0),
                  dplyr::lag(cumsum(bins), n=0, default=0)))
names(bins) <- c("chr", "start", "end")
bins$start <- bins$start + 1 # so that GRanges understands the intervals
gr_bins <- makeGRangesFromDataFrame(bins)

rmap2 <- rmap
rmap2$start <- rmap2$start + 1 # so that GRanges understands the intervals
rec_gr <- makeGRangesFromDataFrame(rmap2, keep.extra.columns=T)
hits <- findOverlaps(query=gr_bins, subject=rec_gr) 
hit_list <- as.data.frame(hits)
names(hit_list) <- c("bins", "rec_bins")
rmap2$rec_bins <- 1:nrow(rmap2)
rec_bins <- merge(rmap2, hit_list) %>%
            group_by(bins) %>%
            mutate(avg_rec=weighted.mean(r, end-start))
rec_bins <- rec_bins %>% distinct(bins, .keep_all=T) 

mmap2 <- mmap 
mmap2$start <- mmap2$start + 1 # so that GRanges understands the intervals
mut_gr <- makeGRangesFromDataFrame(mmap2, keep.extra.columns=T)
hits <- findOverlaps(query=gr_bins, subject=mut_gr) 
hit_list <- as.data.frame(hits)
names(hit_list) <- c("bins", "mut_bins")
mmap2$mut_bins <- 1:nrow(mmap2)
mut_bins <- merge(mmap2, hit_list) %>%
            group_by(bins) %>%
            mutate(avg_mut=weighted.mean(u, end-start))
mut_bins <- mut_bins %>% distinct(bins, .keep_all=T) 

# avg mut rate within each element
elements2 <- elements 
elements2$start <- elements2$start + 1 # so that GRanges understands the intervals
elem_gr <- makeGRangesFromDataFrame(elements2, keep.extra.columns=T)
hits <- findOverlaps(query=elem_gr, subject=mut_gr) 
hit_list <- as.data.frame(hits)
names(hit_list) <- c("elems", "mut_bins")
x <- merge(hit_list, mmap2) %>%
  group_by(elems) %>%
  mutate(avg_mut=weighted.mean(u, end-start)) %>% 
  distinct(., elems, .keep_all=T)
elements$u <- x$avg_mut
# finally writes elements to file
fwrite(elements, "elements.csv.gz")

maps_1kb <- bind_cols(bins,
                      rec_bins["avg_rec"],
                      mut_bins["avg_mut"])

maps_1kb$bin <- 1:nrow(maps_1kb)
maps_1kb$bin_10kb <- (maps_1kb$bin - 1) %/% 10
maps_1kb$bin_100kb <- (maps_1kb$bin - 1) %/% 100
maps_10kb <- maps_1kb %>% group_by(bin_10kb) %>% 
             summarise_at(c("avg_mut", "avg_rec"), mean)
maps_100kb <- maps_1kb %>% group_by(bin_100kb) %>% 
              summarise_at(c("avg_mut", "avg_rec"), mean)

fwrite(maps_1kb, "maps_1kb.csv.gz")
fwrite(maps_10kb, "maps_10kb.csv.gz")
fwrite(maps_100kb, "maps_100kb.csv.gz")

# visualization of shapes of mutation rate distributions
mut_spans <- rgeom(n=100, prob=1/models$avg_mut_spans[m])
mut_spans <- mut_spans[mut_spans>0]

avg_mu <- unique(models$mean_u)
sru <- unique(models$shapes_rate_u)
mus <- as.data.frame(matrix(nrow=length(mut_spans), ncol=length(sru)))
for(i in 1:length(sru)) {
  mus[,i] <- rgamma(n=length(mut_spans), sru[i], rate=sru[i]) * avg_mu
}
names(mus) <- as.character(sru)
tmp <- suppressMessages(setDT(bind_cols(dplyr::lag(cumsum(mut_spans),
          n=1, default=0), dplyr::lag(cumsum(mut_spans), n=0, default=0))))
mmap <- cbind.data.frame(tmp, mus)
names(mmap) <- c("start", "end", as.character(sru))

molten_map <- pivot_longer(mmap, cols=as.character(sru), names_to="shape")
p <- ggplot(data=molten_map, aes(x=start/1e+3, y=value,
                                 color=as.factor(as.numeric(shape)))) +
  geom_step() + theme_bw() +
  scale_color_discrete(name="Shape") +
  scale_x_continuous(breaks=pretty_breaks()) +
  scale_y_continuous(breaks=pretty_breaks(), trans="log10") +
  labs(title="Mutation landscapes for different shape parameters",
       x="Position (kb)", y=expression(mu)) +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=16),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

q <- ggplot(data=molten_map, aes(x=value, fill=as.factor(as.numeric(shape)))) + 
  geom_density(alpha=0.5) + theme_bw() +
  scale_fill_discrete(name="Shape") +
  scale_x_continuous(trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="Density of mutation rate distributions",
       x=expression(mu), y="Density") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("mut_rates_viz.png", plot_grid(p, q, nrow=1),
          base_height=8, base_width=16)

cat("bgs_maps.R is done!\n")