# Date created: 04/03/2024
# Last modified: 25/09/2024
# Author: Gustavo V. Barroso
# This script collects tables generated by bgs_pi.R and bgs_lm.R
# to summarize the results in plots.
# Unlike the former two scripts, this one is meant to be executed in the root
# directory set at the beggining of setup_models.Rmd

suppressMessages({
  library(R.utils)
  library(cowplot)
  library(scales)
  library(tidyverse)
  library(data.table)
  library(GenomicRanges)
  library(ggcorrplot)
  library(interactions)
})

pdf(NULL) # to suppress creation of Rplots.pdf

setwd("~/Data/bgs_lmr/sim_data/chr_models/")

# loads the main tables
models <- fread("models.csv.gz")
#models$cv_u_cv_B <- NA

num_models <- nrow(models)
num_reps <- 10

scale.4d <- function(x) sprintf("%.4f", x) # for adjusting precision in plots

pcor_tbl_1kb <- as.data.frame(matrix(ncol=num_reps, nrow=num_models))
pval_tbl_1kb <- as.data.frame(matrix(ncol=num_reps, nrow=num_models))
pcor_tbl_10kb <- as.data.frame(matrix(ncol=num_reps, nrow=num_models))
pval_tbl_10kb <- as.data.frame(matrix(ncol=num_reps, nrow=num_models))
pcor_tbl_100kb <- as.data.frame(matrix(ncol=num_reps, nrow=num_models))
pval_tbl_100kb <- as.data.frame(matrix(ncol=num_reps, nrow=num_models))
pcor_tbl_1Mb <- as.data.frame(matrix(ncol=num_reps, nrow=num_models))
pval_tbl_1Mb <- as.data.frame(matrix(ncol=num_reps, nrow=num_models))

cv_u_cv_B <- as.data.frame(matrix(ncol=4, nrow=num_models))
names(cv_u_cv_B) <- c(1e+3, 1e+4, 1e+5, 1e+6)

# NOTE: uses output from bgs_maps.R, bgs_lm.R & chr_models.py
for(i in 1:num_models) {
  
  print(Sys.time())
  cat(paste("Visualizing data from model", i, "...\n"))
  
  cv_u_cv_B_1kb <- 0
  cv_u_cv_B_10kb <- 0
  cv_u_cv_B_100kb <- 0
  cv_u_cv_B_1Mb <- 0
  
  for(j in 1:num_reps) {
    
    cat(paste("Rep. ", j, "\n"))
    
    m1kb <- fread(paste("model_", i, "/rep_", j, "/tbl_1kb.csv.gz", sep=""))
    m10kb <- fread(paste("model_", i, "/rep_", j, "/tbl_10kb.csv.gz", sep=""))
    m100kb <- fread(paste("model_", i, "/rep_", j, "/tbl_100kb.csv.gz", sep=""))
    m1Mb <- fread(paste("model_", i, "/rep_", j, "/tbl_1Mb.csv.gz", sep=""))
    
    cv_u_cv_B_1kb <- cv_u_cv_B_1kb + sd(m1kb$avg_mut) / mean(m1kb$avg_mut) / sd(m1kb$B) / mean(m1kb$B)
    cv_u_cv_B_10kb <- cv_u_cv_B_10kb + sd(m10kb$avg_mut) / mean(m10kb$avg_mut) / sd(m10kb$B) / mean(m10kb$B)
    cv_u_cv_B_100kb <- cv_u_cv_B_100kb + sd(m100kb$avg_mut) / mean(m100kb$avg_mut) / sd(m100kb$B) / mean(m100kb$B)
    cv_u_cv_B_1Mb <- cv_u_cv_B_1Mb + sd(m1Mb$avg_mut) / mean(m1Mb$avg_mut) / sd(m1Mb$B) / mean(m1Mb$B)
    
    pc1k <- pcor.test(m1kb$B, m1kb$avg_mut, m1kb$avg_rec, method="spearman")
    pc10k <- pcor.test(m10kb$B, m10kb$avg_mut, m10kb$avg_rec, method="spearman")
    pc100k <- pcor.test(m100kb$B, m100kb$avg_mut, m100kb$avg_rec, method="spearman")
    pc1M <- pcor.test(m1Mb$B, m1Mb$avg_mut, m1Mb$avg_rec, method="spearman")
    
    pcor_tbl_1kb[i, j] <- pc1k$estimate
    pval_tbl_1kb[i, j] <- pc1k$p.value
    pcor_tbl_10kb[i, j] <- pc10k$estimate
    pval_tbl_10kb[i, j] <- pc10k$p.value
    pcor_tbl_100kb[i, j] <- pc100k$estimate
    pval_tbl_100kb[i, j] <- pc100k$p.value
    pcor_tbl_1Mb[i, j] <- pc1M$estimate
    pval_tbl_1Mb[i, j] <- pc1M$p.value
    
    m1kb$bin <- 1:nrow(m1kb)
    m10kb$bin <- 1:nrow(m10kb)
    m100kb$bin <- 1:nrow(m100kb)
    m1Mb$bin <- 1:nrow(m1Mb)
    
    # plots binned maps 
    m1kb_m <- pivot_longer(m1kb, cols=ends_with("pi"), names_to="diversity")
    pi_1kb <- ggplot(data=m1kb_m, aes(x=(bin -1) * 1e+3, y=value, color=diversity)) +
      geom_line(data=m1kb_m) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_pi), max(m1kb$avg_pi)),
                         labels=scale.4d) +
      scale_color_discrete(name=NULL, type=c("plum3", "seagreen3")) +
      labs(title="1 kb", x=NULL, y=expression(pi)) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_text(size=12),
            axis.title.y=element_text(size=16),
            plot.title=element_text(size=20),
            legend.position="inside", legend.position.inside=c(0.925, 0.925)) 
    
    u_1kb <- ggplot(data=m1kb, aes(x=(bin -1) * 1e+3, y=avg_mut)) + 
      geom_line(data=m1kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_mut), max(m1kb$avg_mut)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=expression(mu)) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_text(size=12),
            axis.title.y=element_text(size=16),
            plot.title=element_text(size=20), 
            legend.position="none")
    
    B_1kb <- ggplot(data=m1kb, aes(x=(bin -1) * 1e+3, y=B)) + 
      geom_line(data=m1kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$B), max(m1kb$B)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y="B") +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_text(size=12),
            axis.title.y=element_text(size=16),
            plot.title=element_text(size=20), 
            legend.position="none")
    
    r_1kb <- ggplot(data=m1kb, aes(x=(bin -1) * 1e+3, y=avg_rec)) + 
      geom_line(data=m1kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_rec), max(m1kb$avg_rec)),
                         labels=scientific) +
      labs(title=NULL, x="Position", y="r") +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_text(size=12),
            axis.text.y=element_text(size=12),
            axis.title.y=element_text(size=16),
            plot.title=element_text(size=20),
            legend.position="none")
    
    lands_1kb <- plot_grid(pi_1kb, u_1kb, B_1kb, r_1kb, align='v', ncol=1)

    m10kb_m <- pivot_longer(m10kb, cols=ends_with("pi"), names_to="diversity")
    pi_10kb <- ggplot(data=m10kb_m, aes(x=(bin -1) * 1e+4, y=value, color=diversity)) +
      geom_line(data=m10kb_m) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m10kb$avg_pi), max(m10kb$avg_pi)),
                         labels=scale.4d) +
      scale_color_discrete(name=NULL, type=c("plum3", "seagreen3")) +
      labs(title="10 kb", x=NULL, y=NULL) + 
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="inside", legend.position.inside=c(0.925, 0.925)) 
    
    u_10kb <- ggplot(data=m10kb, aes(x=(bin -1) * 1e+4, y=avg_mut)) + 
      geom_line(data=m10kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_mut), max(m1kb$avg_mut)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    B_10kb <- ggplot(data=m10kb, aes(x=(bin -1) * 1e+4, y=B)) + 
      geom_line(data=m10kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$B), max(m1kb$B)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    r_10kb <- ggplot(data=m10kb, aes(x=(bin -1) * 1e+4, y=avg_rec)) +
      geom_line(data=m10kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(),
                         #limits=c(min(m1kb$avg_rec), max(m1kb$avg_rec)),
                         labels=scientific) +
      labs(title=NULL, x="Position", y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_text(size=12),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20), legend.position="none")
    
    lands_10kb <- plot_grid(pi_10kb, u_10kb, B_10kb, r_10kb, align='v', ncol=1)

    m100kb_m <- pivot_longer(m100kb, cols=ends_with("pi"), names_to="diversity")
    pi_100kb <- ggplot(data=m100kb_m, aes(x=(bin -1) * 1e+5, y=value, color=diversity)) +
      geom_line(data=m100kb_m) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m100kb$avg_pi), max(m100kb$avg_pi)),
                         labels=scale.4d) +
      scale_color_discrete(name=NULL, type=c("plum3", "seagreen3")) +
      labs(title="100 kb", x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="inside", legend.position.inside=c(0.925, 0.925)) 
    
    u_100kb <- ggplot(data=m100kb, aes(x=(bin -1) * 1e+5, y=avg_mut))+
      geom_line(data=m100kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_mut), max(m1kb$avg_mut)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    B_100kb <- ggplot(data=m100kb, aes(x=(bin -1) * 1e+5, y=B))+
      geom_line(data=m100kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(),
                         #limits=c(min(m1kb$B), max(m1kb$B)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    r_100kb <- ggplot(data=m100kb, aes(x=(bin -1) * 1e+5, y=avg_rec)) +
      geom_line(data=m100kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_rec), max(m1kb$avg_rec)),
                         labels=scientific) +
      labs(title=NULL, x="Position", y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_text(size=12),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    lands_100kb <- plot_grid(pi_100kb, u_100kb, B_100kb, r_100kb, align='v', ncol=1)
    
    m1Mb_m <- pivot_longer(m1Mb, cols=ends_with("pi"), names_to="diversity")
    pi_1Mb <- ggplot(data=m1Mb_m, aes(x=(bin -1) * 1e+6, y=value, color=diversity)) +
      geom_line(data=m1Mb_m) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1Mb$avg_pi), max(m1Mb$avg_pi)),
                         labels=scale.4d) +
      scale_color_discrete(name=NULL, type=c("plum3", "seagreen3")) +
      labs(title="1 Mb", x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="inside", legend.position.inside=c(0.925, 0.925)) 
    
    u_1Mb <- ggplot(data=m1Mb, aes(x=(bin -1) * 1e+6, y=avg_mut))+
      geom_line(data=m1Mb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         ##limits=c(min(m1kb$avg_mut), max(m1kb$avg_mut)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    B_1Mb <- ggplot(data=m1Mb, aes(x=(bin -1) * 1e+6, y=B))+
      geom_line(data=m1Mb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(),
                         #limits=c(min(m1kb$B), max(m1kb$B)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    r_1Mb <- ggplot(data=m1Mb, aes(x=(bin -1) * 1e+6, y=avg_rec)) +
      geom_line(data=m1Mb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_rec), max(m1kb$avg_rec)),
                         labels=scientific) +
      labs(title=NULL, x="Position", y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_text(size=12),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    lands_1Mb <- plot_grid(pi_1Mb, u_1Mb, B_1Mb, r_1Mb, align='v', ncol=1)

    lands_scales <- plot_grid(lands_1kb, lands_10kb, lands_100kb, lands_1Mb, nrow=1)
    save_plot(paste("model_", i, "/rep_", j, "/maps.png", sep=""),
              lands_scales, base_height=12, base_width=24)
  }
  
  cv_u_cv_B[i, 1] <- cv_u_cv_B_1kb / num_reps
  cv_u_cv_B[i, 2] <- cv_u_cv_B_10kb / num_reps
  cv_u_cv_B[i, 3] <- cv_u_cv_B_100kb / num_reps
  cv_u_cv_B[i, 4] <- cv_u_cv_B_1Mb / num_reps
}

cv_u_cv_B$model <- 1:nrow(cv_u_cv_B)
models <- merge(cv_u_cv_B, models, by="model")
models <- pivot_longer(models, cols=as.character(c(1e+3, 1e+4, 1e+5, 1e+6)),
                       names_to="scale", values_to="cv_u_cv_B")
models$scale <- as.numeric(models$scale)

# visualization of R^2 and linear coefficients across models
r2_tbl_exp <- data.table()
r2_tbl_sim <- data.table()

coeff_tbl_exp <- data.table()
coeff_tbl_sim <- data.table()

pb <- txtProgressBar(min=1, max=num_models, style=3)
for(i in 1:num_models) {
  
  setTxtProgressBar(pb, i)
  
  # converts num_rep tables of dim (3 x 4: 1kb, 10kb, 100kb x u, B, B:u)
  # into 4 tables of dimension num_reps x 3 (u, B, B:u)
  r2_1kb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  r2_10kb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  r2_100kb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  r2_1Mb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  
  coeff_1kb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  coeff_10kb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  coeff_100kb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  coeff_1Mb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  
  # on expectation
  for(j in 1:num_reps) {
    tmp <- fread(paste("model_", i, "/rep_", j, "/r2_tbl_exp.csv.gz", sep=""))
    
    r2_1kb[j,] <- tmp[1,]
    r2_10kb[j,] <- tmp[2,]
    r2_100kb[j,] <- tmp[3,]
    r2_1Mb[j,] <- tmp[4,]
    
    tmp <- fread(paste("model_", i, "/rep_", j, "/coeff_tbl_exp.csv.gz", sep=""))
    
    coeff_1kb[j,] <- tmp[1,]
    coeff_10kb[j,] <- tmp[2,]
    coeff_100kb[j,] <- tmp[3,]
    coeff_1Mb[j,] <- tmp[4,]
  }
  
  tbl_r2 <- rbind.data.frame(r2_1kb, r2_10kb, r2_100kb, r2_1Mb)
  names(tbl_r2) <- c("u", "B", "B:u", "scale")
  tbl_r2$model <- i
  tbl_r2$rep <- rep(1:10, 4)
  
  tbl_coeff <- rbind.data.frame(coeff_1kb, coeff_10kb, coeff_100kb, coeff_1Mb)
  names(tbl_coeff) <- c("u", "B", "B:u", "scale")
  tbl_coeff$model <- i
  tbl_coeff$rep <- rep(1:10, 4)

  r2_tbl_exp <- rbind.data.frame(r2_tbl_exp, tbl_r2)
  coeff_tbl_exp <- rbind.data.frame(coeff_tbl_exp, tbl_coeff)
  
  # with mutational variance
  for(j in 1:num_reps) {
    tmp <- fread(paste("model_", i, "/rep_", j, "/r2_tbl_sim.csv.gz", sep=""))
    
    r2_1kb[j,] <- tmp[1,]
    r2_10kb[j,] <- tmp[2,]
    r2_100kb[j,] <- tmp[3,]
    r2_1Mb[j,] <- tmp[4,]
    
    tmp <- fread(paste("model_", i, "/rep_", j, "/coeff_tbl_sim.csv.gz", sep=""))
    
    coeff_1kb[j,] <- tmp[1,]
    coeff_10kb[j,] <- tmp[2,]
    coeff_100kb[j,] <- tmp[3,]
    coeff_1Mb[j,] <- tmp[4,]
  }
  
  tbl_r2 <- rbind.data.frame(r2_1kb, r2_10kb, r2_100kb, r2_1Mb)
  names(tbl_r2) <- c("u", "B", "B:u", "scale")
  tbl_r2$model <- i
  tbl_r2$rep <- rep(1:10, 4)
  
  tbl_coeff <- rbind.data.frame(coeff_1kb, coeff_10kb, coeff_100kb, coeff_1Mb)
  names(tbl_coeff) <- c("u", "B", "B:u", "scale")
  tbl_coeff$model <- i
  tbl_coeff$rep <- rep(1:10, 4)
  
  coeff_tbl_sim <- rbind.data.frame(coeff_tbl_sim, tbl_coeff)
  r2_tbl_sim <- rbind.data.frame(r2_tbl_sim, tbl_r2)
}
close(pb)

r2s_exp <- r2_tbl_exp %>% group_by(model, scale) %>% 
                          summarize_at(vars(u, B, `B:u`), 
                                       list(avg=mean, sd=sd))

r2s_sim <- r2_tbl_sim %>% group_by(model, scale) %>% 
                          summarize_at(vars(u, B, `B:u`), 
                                       list(avg=mean, sd=sd))

cs_exp <- coeff_tbl_exp %>% group_by(model, scale) %>% 
  summarize_at(vars(u, B, `B:u`), 
               list(avg=mean, sd=sd))

cs_sim <- coeff_tbl_sim %>% group_by(model, scale) %>% 
  summarize_at(vars(u, B, `B:u`), 
               list(avg=mean, sd=sd))

fwrite(r2s_exp, "r2_exp_tbl_models.csv")
fwrite(r2s_sim, "r2_sim_tbl_models.csv")

fwrite(cs_exp, "coeff_exp_tbl_models.csv")
fwrite(cs_sim, "coeff_sim_tbl_models.csv")

# plots of R^2 per variable per model
pb <- txtProgressBar(min=1, max=num_models, style=3)
for(i in 1:num_models) {
  
  setTxtProgressBar(pb, i)
  
  molten_avgs <- pivot_longer(r2s_exp, cols=ends_with("avg"), names_to="variable")
  p <- ggplot(data=filter(molten_avgs, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "B:u", "u")) +
    scale_x_continuous(breaks=unique(molten_avgs$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(Mean over replicates)"),
         x="Map Scale (kb)", y="Variance Explained (%)") +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16),
          legend.position="bottom")
  
  molten_sds <- pivot_longer(r2s_exp, cols=ends_with("sd"), names_to="variable")
  q <- ggplot(data=filter(molten_sds, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "B:u", "u")) +
    scale_x_continuous(breaks=unique(molten_sds$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(SD over replicates)"),
         x="Map Scale (kb)", y=NULL) +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16), 
          legend.position="bottom")
  
  save_plot(paste("model_", i, "_exp_r2.png", sep=""), plot_grid(p, q, nrow=1), 
            base_height=10, base_width=15)
  
  molten_avgs <- pivot_longer(r2s_sim, cols=ends_with("avg"), names_to="variable")
  p <- ggplot(data=filter(molten_avgs, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "B:u", "u")) +
    scale_x_continuous(breaks=unique(molten_avgs$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(Mean over replicates)"),
         x="Map Scale (kb)", y="Variance explained (%)") +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16),
          legend.position="bottom")
  
  molten_sds <- pivot_longer(r2s_sim, cols=ends_with("sd"), names_to="variable")
  q <- ggplot(data=filter(molten_sds, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "B:u", "u")) +
    scale_x_continuous(breaks=unique(molten_sds$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(SD over replicates)"),
         x="Map Scale (kb)", y=NULL) +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16), 
          legend.position="bottom")
  
  save_plot(paste("model_", i, "_sim_r2.png", sep=""), plot_grid(p, q, nrow=1), 
            base_height=10, base_width=15)
}
close(pb)

# plots of coeffs per variable per model
pb <- txtProgressBar(min=1, max=num_models, style=3)
for(i in 1:num_models) {
  
  setTxtProgressBar(pb, i)
  
  molten_avgs <- pivot_longer(cs_exp, cols=ends_with("avg"), names_to="variable")
  p <- ggplot(data=filter(molten_avgs, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "B:u", "u")) +
    scale_x_continuous(breaks=unique(molten_avgs$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(Mean over replicates)"),
         x="Map Scale (kb)", y="Linear Coefficient") +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16),
          legend.position="bottom")
  
  molten_sds <- pivot_longer(cs_exp, cols=ends_with("sd"), names_to="variable")
  q <- ggplot(data=filter(molten_sds, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "B:u", "u")) +
    scale_x_continuous(breaks=unique(molten_sds$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(SD over replicates)"),
         x="Map Scale (kb)", y=NULL) +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16), 
          legend.position="bottom")
  
  save_plot(paste("model_", i, "_exp_coeff.png", sep=""), plot_grid(p, q, nrow=1), 
            base_height=10, base_width=15)
  
  molten_avgs <- pivot_longer(cs_sim, cols=ends_with("avg"), names_to="variable")
  p <- ggplot(data=filter(molten_avgs, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "B:u", "u")) +
    scale_x_continuous(breaks=unique(molten_avgs$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(Mean over replicates)"),
         x="Map Scale (kb)", y="Linear Coefficient") +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16),
          legend.position="bottom")
  
  molten_sds <- pivot_longer(cs_sim, cols=ends_with("sd"), names_to="variable")
  q <- ggplot(data=filter(molten_sds, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "B:u", "u")) +
    scale_x_continuous(breaks=unique(molten_sds$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(SD over replicates)"),
         x="Map Scale (kb)", y=NULL) +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16), 
          legend.position="bottom")
  
  save_plot(paste("model_", i, "_sim_coeff.png", sep=""), plot_grid(p, q, nrow=1), 
            base_height=10, base_width=15)
}
close(pb)

# we combine plots across models
## expected pi
### R2
r2s_exp_f <- dplyr::select(r2s_exp, -starts_with("B:u")) %>%
             dplyr::select(., -ends_with("sd"))

r2_exp_models <- merge(models, r2s_exp_f,by=c("model", "scale"))
r2_exp_models$source_pi <- "exp"
m_r2_exp_models <- pivot_longer(r2_exp_models, cols=ends_with("avg"), names_to="var")

### coeffs
coeff_exp_f <- dplyr::select(cs_exp, -starts_with("B:u")) %>%
               dplyr::select(., -ends_with("sd")) %>%
               mutate(., ratio = u_avg / B_avg)

coeff_exp_models <- merge(models, coeff_exp_f, by=c("model", "scale"))
coeff_exp_models$source_pi <- "exp"
m_coeff_exp_models <- pivot_longer(coeff_exp_models, 
                                   cols=c("ratio", ends_with("avg")),
                                   names_to="var")

## simulated pi
### R2
r2s_sim_f <- dplyr::select(r2s_sim, -starts_with("B:u")) %>%
             dplyr::select(., -ends_with("sd")) 

r2_sim_models <- merge(models, r2s_sim_f, by=c("model", "scale"))
r2_sim_models$source_pi <- "sim"
m_r2_sim_models <- pivot_longer(r2_sim_models, cols=ends_with("avg"), names_to="var")

### coeffs
coeff_sim_f <- dplyr::select(cs_sim, -starts_with("B:u")) %>%
               dplyr::select(., -ends_with("sd")) %>%
               mutate(., ratio = u_avg / B_avg)

coeff_sim_models <- merge(models, coeff_sim_f, by=c("model", "scale"))
coeff_sim_models$source_pi <- "sim"
m_coeff_sim_models <- pivot_longer(coeff_sim_models,
                                   cols=c("ratio", ends_with("avg")),
                                   names_to="var")

m_coeff_models <- rbind.data.frame(m_coeff_exp_models, m_coeff_sim_models)
m_r2_models <- rbind.data.frame(m_r2_exp_models, m_r2_sim_models)

fwrite(m_coeff_models, "coeff_models.csv.gz")
fwrite(m_r2_models, "r2_models.csv.gz")

## R2 plots
p1 <- ggplot(data=filter(m_r2_models, num_exons==600, shapes_rate_r==1, avg_rec_spans==1e+3),
       aes(x=scale/1e+3, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u"))+
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_r2_exp_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("2% exonic, rec map exponential/1kb, ",
                   "cols->shape(u), rows->avg mut. span"),
       x="Map Scale (kb)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

p2 <- ggplot(data=filter(m_r2_models, num_exons==1500, shapes_rate_r==1, avg_rec_spans==1e+3),
       aes(x=scale/1e+3, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u"))+
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_r2_exp_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, rec map exponential/1kb, ",
                   "cols->shape(u), rows->avg mut. span"),
       x="Map Scale (kb)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

p3 <- ggplot(data=filter(m_r2_models, num_exons==3000, shapes_rate_r==1, avg_rec_spans==1e+3),
       aes(x=scale/1e+3, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u")) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_r2_exp_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("10% exonic, rec map exponential/1kb, ",
                   "cols->shape(u), rows->avg mut. span"),
       x="Map Scale (kb)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("r2_exonic_0.02.png", p1, base_width=14, base_height=9)
save_plot("r2_exonic_0.05.png", p2, base_width=14, base_height=9)
save_plot("r2_exonic_0.1.png", p3, base_width=14, base_height=9)

x1kb <- ggplot(data=filter(m_r2_models, num_exons==600, scale==1e+3),
             aes(x=cv_u_cv_B, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+shapes_rate_r~avg_rec_spans) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u"))+
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=c(1, 10, 100), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="2% exonic, 1kb scale, rows>shape(r), rows->avg rec. span",
       x="CV(u) / CV(B)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

x10kb <- ggplot(data=filter(m_r2_models, num_exons==600, scale==1e+4),
             aes(x=cv_u_cv_B, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+shapes_rate_r~avg_rec_spans) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u"))+
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=c(1, 10, 100), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="5% exonic, 10kb scale, rows>shape(r), rows->avg rec. span",
       x="CV(u) / CV(B)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

x100kb <- ggplot(data=filter(m_r2_models, num_exons==600, scale==1e+5),
             aes(x=cv_u_cv_B, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+shapes_rate_r~avg_rec_spans) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u"))+
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=c(1, 10, 100), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="2% exonic, 100kb scale, rows>shape(r), rows->avg rec. span",
       x="CV(u) / CV(B)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

x1Mb <- ggplot(data=filter(m_r2_models, num_exons==600, scale==1e+6),
                 aes(x=cv_u_cv_B, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+shapes_rate_r~avg_rec_spans) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u"))+
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=c(1, 10, 100), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="2% exonic, 1Mb scale, rows>shape(r), rows->avg rec. span",
       x="CV(u) / CV(B)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("r2_exonic_0.02_1kb.png", x1kb, base_width=14, base_height=9)
save_plot("r2_exonic_0.02_10kb.png", x10kb, base_width=14, base_height=9)
save_plot("r2_exonic_0.02_100kb.png", x100kb, base_width=14, base_height=9)
save_plot("r2_exonic_0.02_1Mb.png", x1Mb, base_width=14, base_height=9)

q1 <- ggplot(data=filter(m_r2_models, var=="u_avg", num_exons==3000, shapes_rate_r==1),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("10% exonic, var rec HIGH, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

q2 <- ggplot(data=filter(m_r2_models, var=="u_avg", num_exons==3000, shapes_rate_r==3),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("10% exonic, var rec MID, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

q3 <- ggplot(data=filter(m_r2_models, var=="u_avg", num_exons==3000, shapes_rate_r==10),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("10% exonic, var rec LOW, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("r2_u_exons_0.1_shape_r_1.png", q1, base_height=8, base_width=16)
save_plot("r2_u_exons_0.1_shape_r_3.png", q2, base_height=8, base_width=16)
save_plot("r2_u_exons_0.1_shape_r_10.png", q3, base_height=8, base_width=16)

y1kb <- ggplot(data=filter(m_r2_models, var=="u_avg", scale==1e+3),
             aes(x=cv_u_cv_B, y=value, shape=as.factor(num_exons), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_rec_spans~shapes_rate_r) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2), name="# Exons") +
  scale_x_continuous(breaks=c(1, 10), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="1kb, cols->avg_rec_spans, rows->shapes_rate_r",
       x="CV(u) / CV(B)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

y10kb <- ggplot(data=filter(m_r2_models, var=="u_avg", scale==1e+4),
               aes(x=cv_u_cv_B, y=value, shape=as.factor(num_exons), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_rec_spans~shapes_rate_r) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2), name="# Exons") +
  scale_x_continuous(breaks=c(1, 10), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="10kb, cols->avg_rec_spans, rows->shapes_rate_r",
       x="CV(u) / CV(B)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

y100kb <- ggplot(data=filter(m_r2_models, var=="u_avg", scale==1e+5),
                aes(x=cv_u_cv_B, y=value, shape=as.factor(num_exons), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_rec_spans~shapes_rate_r) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2), name="# Exons") +
  scale_x_continuous(breaks=c(1, 10), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="100kb, cols->avg_rec_spans, rows->shapes_rate_r",
       x="CV(u) / CV(B)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

y1Mb <- ggplot(data=filter(m_r2_models, var=="u_avg", scale==1e+6),
                 aes(x=cv_u_cv_B, y=value, shape=as.factor(num_exons), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_rec_spans~shapes_rate_r) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2), name="# Exons") +
  scale_x_continuous(breaks=c(1, 10), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="1Mb, cols->avg_rec_spans, rows->shapes_rate_r",
       x="CV(u) / CV(B)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("r2_u_1kb.png", y1kb, base_height=8, base_width=16)
save_plot("r2_u_10kb.png", y10kb, base_height=8, base_width=16)
save_plot("r2_u_100kb.png", y100kb, base_height=8, base_width=16)
save_plot("r2_u_1Mb.png", y1Mb, base_height=8, base_width=16)

r1 <- ggplot(data=filter(m_r2_models, var=="u_avg", num_exons==1500, shapes_rate_r==1),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, var rec HIGH, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

r2 <- ggplot(data=filter(m_r2_models, var=="u_avg", num_exons==1500, shapes_rate_r==3),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, var rec MID, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

r3 <- ggplot(data=filter(m_r2_models, var=="u_avg", num_exons==1500, shapes_rate_r==10),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec Span (kb)") +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, var rec LOW, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("r2_u_exons_0.05_shape_r_1.png", r1, base_height=8, base_width=16)
save_plot("r2_u_exons_0.05_shape_r_3.png", r2, base_height=8, base_width=16)
save_plot("r2_u_exons_0.05_shape_r_10.png", r3, base_height=8, base_width=16)

s1 <- ggplot(data=filter(m_r2_models, var=="u_avg", num_exons==600, shapes_rate_r==1),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, var rec HIGH, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

s2 <- ggplot(data=filter(m_r2_models, var=="u_avg", num_exons==600, shapes_rate_r==3),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, var rec MID, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

s3 <- ggplot(data=filter(m_r2_models, var=="u_avg", num_exons==600, shapes_rate_r==10),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec Span (kb)") +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, var rec LOW, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("r2_u_exons_0.02_shape_r_1.png", s1, base_height=8, base_width=16)
save_plot("r2_u_exons_0.02_shape_r_3.png", s2, base_height=8, base_width=16)
save_plot("r2_u_exons_0.02_shape_r_10.png", s3, base_height=8, base_width=16)

## coeff plots
p1 <- ggplot(data=filter(m_coeff_models, num_exons==600, var!="ratio", shapes_rate_r==1, avg_rec_spans==1e+3),
             aes(x=scale/1e+3, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u")) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("Mean coeff over replicates, cols->shape(u), rows->avg mut. span"),
       x="Map Scale (kb)", y="Std Linear Coeff.") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

p2 <- ggplot(data=filter(m_coeff_models, num_exons==1500, var!="ratio", shapes_rate_r==1, avg_rec_spans==1e+3),
             aes(x=scale/1e+3, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u")) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("Mean coeff over replicates, cols->shape(u), rows->avg mut. span"),
       x="Map Scale (kb)", y="Std Linear Coeff.") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

p3 <- ggplot(data=filter(m_coeff_models, num_exons==3000, var!="ratio", shapes_rate_r==1, avg_rec_spans==1e+3),
             aes(x=scale/1e+3, y=value, shape=var, color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u")) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("Mean coeff over replicates, cols->shape(u), rows->avg mut. span"),
       x="Map Scale (kb)", y="Std Linear Coeff.") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("coeff_exonic_0.02.png", p1, base_width=14, base_height=9)
save_plot("coeff_exonic_0.05.png", p2, base_width=14, base_height=9)
save_plot("coeff_exonic_0.1.png", p3, base_width=14, base_height=9)

q1 <- ggplot(data=filter(m_coeff_models, var=="ratio", num_exons==3000, shapes_rate_r==1),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("10% exonic, var rec HIGH, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

q2 <- ggplot(data=filter(m_coeff_models, var=="ratio", num_exons==3000, shapes_rate_r==3),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("10% exonic, var rec MID, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

q3 <- ggplot(data=filter(m_coeff_models, var=="ratio", num_exons==3000, shapes_rate_r==10),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("10% exonic, var rec LOW, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("coeff_ratios_exons_0.1_shape_r_1.png", q1, base_height=8, base_width=16)
save_plot("coeff_ratios_exons_0.1_shape_r_3.png", q2, base_height=8, base_width=16)
save_plot("coeff_ratios_exons_0.1_shape_r_10.png", q3, base_height=8, base_width=16)

r1 <- ggplot(data=filter(m_coeff_models, var=="ratio", num_exons==1500, shapes_rate_r==1),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, var rec HIGH, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

r2 <- ggplot(data=filter(m_coeff_models, var=="ratio", num_exons==1500, shapes_rate_r==3),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, var rec MID, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

r3 <- ggplot(data=filter(m_coeff_models, var=="ratio", num_exons==1500, shapes_rate_r==10),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans))) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec Span (kb)") +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("5% exonic, var rec LOW, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("coeff_u_exons_0.05_shape_r_1.png", r1, base_height=8, base_width=16)
save_plot("coeff_u_exons_0.05_shape_r_3.png", r2, base_height=8, base_width=16)
save_plot("coeff_u_exons_0.05_shape_r_10.png", r3, base_height=8, base_width=16)

s1 <- ggplot(data=filter(m_coeff_models, var=="ratio", num_exons==600, shapes_rate_r==1),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("2% exonic, var rec HIGH, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)",  y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

s2 <- ggplot(data=filter(m_coeff_models, var=="ratio", num_exons==600, shapes_rate_r==3),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec. Span (kb)") +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("2% exonic, var rec MID, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)",  y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

s3 <- ggplot(data=filter(m_coeff_models, var=="ratio", num_exons==600, shapes_rate_r==10),
             aes(x=scale/1e+3, y=value, shape=as.factor(avg_rec_spans), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 8), name="Avg. Rec Span (kb)") +
  scale_x_continuous(breaks=unique(m_coeff_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("2% exonic, var rec LOW, ", 
                   "cols->shape mu dist., rows->avg mu span"),
       x="Map Scale (kb)",  y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("coeff_ratios_exons_0.02_shape_r_1.png", s1, base_height=8, base_width=16)
save_plot("coeff_ratios_exons_0.02_shape_r_3.png", s2, base_height=8, base_width=16)
save_plot("coeff_ratios_exons_0.02_shape_r_10.png", s3, base_height=8, base_width=16)

z1kb <- ggplot(data=filter(m_coeff_models, var=="ratio", scale==1e+3),
               aes(x=cv_u_cv_B, y=value, shape=as.factor(num_exons), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_rec_spans~shapes_rate_r) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2), name="# Exons") +
  scale_x_continuous(breaks=c(1, 10, 100)) +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="1kb, cols->avg_rec_spans, rows->shapes_rate_r",
       x="CV(u) / CV(B)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

z10kb <- ggplot(data=filter(m_coeff_models, var=="ratio", scale==1e+4),
                aes(x=cv_u_cv_B, y=value, shape=as.factor(num_exons), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_rec_spans~shapes_rate_r) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2), name="# Exons") +
  scale_x_continuous(breaks=c(1, 10, 100)) +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="10kb, cols->avg_rec_spans, rows->shapes_rate_r",
       x="CV(u) / CV(B)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

z100kb <- ggplot(data=filter(m_coeff_models, var=="ratio", scale==1e+5),
               aes(x=cv_u_cv_B, y=value, shape=as.factor(num_exons), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_rec_spans~shapes_rate_r) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2), name="# Exons") +
  scale_x_continuous(breaks=c(1, 10, 100)) +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="1kb, cols->avg_rec_spans, rows->shapes_rate_r",
       x="CV(u) / CV(B)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

z1Mb <- ggplot(data=filter(m_coeff_models, var=="ratio", scale==1e+6),
               aes(x=cv_u_cv_B, y=value, shape=as.factor(num_exons), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_grid(+avg_rec_spans~shapes_rate_r) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2), name="# Exons") +
  scale_x_continuous(breaks=c(1, 10, 100)) +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title="1Mb, cols->avg_rec_spans, rows->shapes_rate_r",
       x="CV(u) / CV(B)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("coeff_ratios_1kb.png", z1kb, base_height=8, base_width=16)
save_plot("coeff_ratios_10kb.png", z10kb, base_height=8, base_width=16)
save_plot("coeff_ratios_100kb.png", z100kb, base_height=8, base_width=16)
save_plot("coeff_ratios_1Mb.png", z1Mb, base_height=8, base_width=16)

w <- ggplot(data=filter(m_coeff_models, var=="ratio", avg_rec_spans==1e+5, shapes_rate_r==1),
            aes(x=cv_u_cv_B, y=value, shape=as.factor(num_exons), color=source_pi)) +
  geom_line() + geom_point(size=4) + theme_bw() +
  facet_wrap(~scale) +
  scale_color_discrete(name="source pi", type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2), name="# Exons") +
  scale_x_continuous(breaks=c(0.1, 1, 10), trans="log10") +
  scale_y_continuous(breaks=c(0.1, 1, 10), trans="log10") +
  labs(title=NULL, x="CV(u) / CV(B)", y="Ratio of Linear Coeffs (u/B)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("coeff_ratios_scale.png", w, base_height=8, base_width=16)


# meta linear models (pi exp)
## 1 kb
std_r2_1kb <- as.data.frame(r2_exp_models %>%
                            filter(., scale==1e+3) %>% 
                            dplyr::select(c(u_avg, B_avg,
                                            num_exons,
                                            shapes_rate_u,
                                            shapes_rate_r,
                                            avg_mut_spans,
                                            avg_mut_spans)) %>%
                            apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_1kb <- lm(u_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                       avg_mut_spans + avg_rec_spans)^2, data=std_r2_1kb)
m_B_1kb <- lm(B_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                       avg_mut_spans + avg_rec_spans)^2, data=std_r2_1kb)

summary(m_u_1kb)
summary(m_B_1kb)

## 10 kb
std_r2_10kb <- as.data.frame(r2_exp_models %>% 
                              filter(., scale==1e+4) %>% 
                              dplyr::select(c(u_avg, B_avg,
                                              num_exons,
                                              shapes_rate_u,
                                              shapes_rate_r,
                                              avg_mut_spans,
                                              avg_mut_spans)) %>%
                              apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_10kb <- lm(u_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                          avg_mut_spans + avg_rec_spans)^2, data=std_r2_10kb)
m_B_10kb <- lm(B_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                          avg_mut_spans + avg_rec_spans)^2, data=std_r2_10kb)

summary(m_u_10kb)
summary(m_B_10kb)

## 100 kb
std_r2_100kb <- as.data.frame(r2_exp_models %>% 
                              filter(., scale==1e+5) %>% 
                              dplyr::select(c(u_avg, B_avg,
                                              num_exons,
                                              shapes_rate_u,
                                              shapes_rate_r,
                                              avg_mut_spans,
                                              avg_mut_spans)) %>%
                              apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_100kb <- lm(u_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                           avg_mut_spans + avg_rec_spans)^2, data=std_r2_100kb)
m_B_100kb <- lm(B_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                           avg_mut_spans + avg_rec_spans)^2, data=std_r2_100kb)

summary(m_u_100kb)
summary(m_B_100kb)

## 1 Mb
std_r2_1Mb <- as.data.frame(r2_exp_models %>% 
                            filter(., scale==1e+6) %>% 
                            dplyr::select(c(u_avg, B_avg,
                                            num_exons,
                                            shapes_rate_u,
                                            shapes_rate_r,
                                            avg_mut_spans,
                                            avg_mut_spans)) %>%
                            apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_1Mb <- lm(u_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                       avg_mut_spans + avg_rec_spans)^2, data=std_r2_1Mb)
m_B_1Mb <- lm(B_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                           avg_mut_spans + avg_rec_spans)^2, data=std_r2_1Mb)

summary(m_u_1Mb)
summary(m_B_1Mb)

# mut
meta_lm_u <- rbind.data.frame(m_u_1kb$coefficients,
                              m_u_10kb$coefficients,
                              m_u_100kb$coefficients,
                              m_u_1Mb$coefficients)
names(meta_lm_u) <- names(m_u_1kb$coefficients)

meta_lm_u <- dplyr::select(meta_lm_u, c("shapes_rate_u",
                                        "avg_mut_spans",
                                        "num_exons",
                                        "shapes_rate_r",
                                        "avg_rec_spans"))

meta_lm_u$bin_size <- c(1e+3, 1e+4, 1e+5, 1e+6)
meta_lm_u$response <- "Mu"

mmlm_mu <- pivot_longer(meta_lm_u, cols=names(meta_lm_u)[1:(ncol(meta_lm_u)-2)],
                        names_to="var", values_to="coeff")

# B-val
meta_lm_B <- rbind.data.frame(m_B_1kb$coefficients,
                              m_B_10kb$coefficients,
                              m_B_100kb$coefficients,
                              m_B_1Mb$coefficients)
names(meta_lm_B) <- names(m_B_1kb$coefficients)

meta_lm_B <- dplyr::select(meta_lm_B, c("shapes_rate_u",
                                        "avg_mut_spans",
                                        "num_exons",
                                        "shapes_rate_r",
                                        "avg_rec_spans"))

meta_lm_B$bin_size <- c(1e+3, 1e+4, 1e+5, 1e+6)
meta_lm_B$response <- "B"

mmlm_B <- pivot_longer(meta_lm_B, cols=names(meta_lm_B)[1:(ncol(meta_lm_B)-2)],
                       names_to="var", values_to="coeff")

mmlm_tbl <- rbind.data.frame(mmlm_mu, mmlm_B)

meta_lm <- ggplot(data=mmlm_tbl, aes(x=var, y=coeff, shape=as.factor(bin_size), color=response)) +
  geom_point(size=4) + theme_bw() +
  geom_hline(yintercept=0, linetype="dashed") +
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_color_discrete(name=NULL, type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 4), name="Bin Size") +
  labs(title="Meta Linear Model for Variance Explained by 'Response'",
       x="Variable", y="Coefficient") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(angle=90, size=12, vjust=0.5, hjust=1.0),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("meta_lm_pi_exp.png", meta_lm, base_height=8, base_width=10)

## 1 kb
std_r2_1kb <- as.data.frame(r2_sim_models %>%
                            filter(., scale==1e+3) %>% 
                            dplyr::select(c(u_avg, B_avg,
                                            num_exons,
                                            shapes_rate_u,
                                            shapes_rate_r,
                                            avg_mut_spans,
                                            avg_mut_spans)) %>%
                            apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_1kb <- lm(u_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                         avg_mut_spans + avg_rec_spans)^2, data=std_r2_1kb)
m_B_1kb <- lm(B_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                         avg_mut_spans + avg_rec_spans)^2, data=std_r2_1kb)

summary(m_u_1kb)
summary(m_B_1kb)

## 10 kb
std_r2_10kb <- as.data.frame(r2_sim_models %>% 
                             filter(., scale==1e+4) %>% 
                             dplyr::select(c(u_avg, B_avg,
                                             num_exons,
                                             shapes_rate_u,
                                             shapes_rate_r,
                                             avg_mut_spans,
                                             avg_mut_spans)) %>%
                             apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_10kb <- lm(u_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                          avg_mut_spans + avg_rec_spans)^2, data=std_r2_10kb)
m_B_10kb <- lm(B_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                          avg_mut_spans + avg_rec_spans)^2, data=std_r2_10kb)

summary(m_u_10kb)
summary(m_B_10kb)

## 100 kb
std_r2_100kb <- as.data.frame(r2_sim_models %>% 
                              filter(., scale==1e+5) %>% 
                              dplyr::select(c(u_avg, B_avg,
                                              num_exons,
                                              shapes_rate_u,
                                              shapes_rate_r,
                                              avg_mut_spans,
                                              avg_mut_spans)) %>%
                              apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_100kb <- lm(u_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                           avg_mut_spans + avg_rec_spans)^2, data=std_r2_100kb)
m_B_100kb <- lm(B_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                           avg_mut_spans + avg_rec_spans)^2, data=std_r2_100kb)

summary(m_u_100kb)
summary(m_B_100kb)

## 1 Mb
std_r2_1Mb <- as.data.frame(r2_sim_models %>% 
                            filter(., scale==1e+6) %>% 
                            dplyr::select(c(u_avg, B_avg,
                                            num_exons,
                                            shapes_rate_u,
                                            shapes_rate_r,
                                            avg_mut_spans,
                                            avg_mut_spans)) %>%
                            apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_1Mb <- lm(u_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                         avg_mut_spans + avg_rec_spans)^2, data=std_r2_1Mb)
m_B_1Mb <- lm(B_avg ~ (num_exons + shapes_rate_u + shapes_rate_r + 
                         avg_mut_spans + avg_rec_spans)^2, data=std_r2_1Mb)

summary(m_u_1Mb)
summary(m_B_1Mb)

# mut
meta_lm_u <- rbind.data.frame(m_u_1kb$coefficients,
                              m_u_10kb$coefficients,
                              m_u_100kb$coefficients,
                              m_u_1Mb$coefficients)
names(meta_lm_u) <- names(m_u_1kb$coefficients)

meta_lm_u <- dplyr::select(meta_lm_u, c("shapes_rate_u",
                                        "avg_mut_spans",
                                        "num_exons",
                                        "shapes_rate_r",
                                        "avg_rec_spans"))

meta_lm_u$bin_size <- c(1e+3, 1e+4, 1e+5, 1e+6)
meta_lm_u$response <- "Mu"

mmlm_mu <- pivot_longer(meta_lm_u, cols=names(meta_lm_u)[1:(ncol(meta_lm_u)-2)],
                        names_to="var", values_to="coeff")

# B-val
meta_lm_B <- rbind.data.frame(m_B_1kb$coefficients,
                              m_B_10kb$coefficients,
                              m_B_100kb$coefficients,
                              m_B_1Mb$coefficients)
names(meta_lm_B) <- names(m_B_1kb$coefficients)

meta_lm_B <- dplyr::select(meta_lm_B, c("shapes_rate_u",
                                        "avg_mut_spans",
                                        "num_exons",
                                        "shapes_rate_r",
                                        "avg_rec_spans"))

meta_lm_B$bin_size <- c(1e+3, 1e+4, 1e+5, 1e+6)
meta_lm_B$response <- "B"

mmlm_B <- pivot_longer(meta_lm_B, cols=names(meta_lm_B)[1:(ncol(meta_lm_B)-2)],
                       names_to="var", values_to="coeff")

mmlm_tbl <- rbind.data.frame(mmlm_mu, mmlm_B)

meta_lm <- ggplot(data=mmlm_tbl, aes(x=var, y=coeff, shape=as.factor(bin_size), color=response)) +
  geom_point(size=4) + theme_bw() +
  geom_hline(yintercept=0, linetype="dashed") +
  scale_y_continuous(breaks=pretty_breaks()) +
  scale_color_discrete(name=NULL, type=c("plum3", "seagreen3")) +
  scale_shape_manual(values=c(0, 1, 2, 4), name="Bin Size") +
  labs(title="Meta Linear Model for Variance Explained by 'Response'",
       x="Variable", y="Coefficient") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(angle=90, size=12, vjust=0.5, hjust=1.0),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("meta_lm_pi_sim.png", meta_lm, base_height=8, base_width=10)

cat("bgs_viz.R is done!\n")
