# Date created: 04/03/2024
# Last modified: 12/03/2024
# Author: Gustavo V. Barroso
# This script collects tables generated by bgs_pi.R and bgs_lm.R
# to summarize the results in plots.
# Unlike the former two scripts, this one is meant to be executed in the root
# directory set at the beggining of setup_models.Rmd

suppressMessages({
  library(R.utils)
  library(cowplot)
  library(scales)
  library(tidyverse)
  library(data.table)
  library(GenomicRanges)
  library(ggcorrplot)
  library(interactions)
})

pdf(NULL) # to suppress creation of Rplots.pdf

# loads the main tables
models <- fread("models.csv")
models <- models[1:100,]
num_models <- nrow(models)
num_reps <- 10

# tables with R^2 for each model / scale
r2_mdl_1kb <- as.data.frame(matrix(nrow=num_reps, ncol=5))
r2_mdl_10kb <- as.data.frame(matrix(nrow=num_reps, ncol=5))
r2_mdl_100kb <- as.data.frame(matrix(nrow=num_reps, ncol=5))

scale.4d <- function(x) sprintf("%.4f", x) # for adjusting precision in plots

# NOTE: uses output from bgs_maps.R, bgs_pi.R & bgs_lm.R 
for(i in 1:num_models) {
  
  print(Sys.time())
  cat(paste("Visualizing data from model", i, "...\n"))
  
  for(j in 1:num_reps) {
    
    m1kb <- fread(paste("model_", i, "/rep_", j, "/tbl_1kb.csv", sep=""))
    m10kb <- fread(paste("model_", i, "/rep_", j, "/tbl_10kb.csv", sep=""))
    m100kb <- fread(paste("model_", i, "/rep_", j, "/tbl_100kb.csv",sep=""))
    m1Mb <- fread(paste("model_", i, "/rep_", j, "/tbl_1Mb.csv",sep=""))
  
    m1kb$bin <- 1:nrow(m1kb)
    m10kb$bin <- 1:nrow(m10kb)
    m100kb$bin <- 1:nrow(m100kb)
    m1Mb$bin <- 1:nrow(m1Mb)
    
    # plots binned maps 
    pi_1kb <- ggplot(data=m1kb, aes(x=(bin -1) * 1e+3, y=avg_pi)) +
      geom_line(data=m1kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_pi), max(m1kb$avg_pi)),
                         labels=scale.4d) +
      labs(title="1 kb", x=NULL, y=expression(pi)) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_text(size=12),
            axis.title.y=element_text(size=16),
            plot.title=element_text(size=20),
            legend.position="none") 
    
    u_1kb <- ggplot(data=m1kb, aes(x=(bin -1) * 1e+3, y=avg_mut)) + 
      geom_line(data=m1kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_mut), max(m1kb$avg_mut)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=expression(mu)) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_text(size=12),
            axis.title.y=element_text(size=16),
            plot.title=element_text(size=20), 
            legend.position="none")
    
    B_1kb <- ggplot(data=m1kb, aes(x=(bin -1) * 1e+3, y=B)) + 
      geom_line(data=m1kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$B), max(m1kb$B)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y="B") +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_text(size=12),
            axis.title.y=element_text(size=16),
            plot.title=element_text(size=20), 
            legend.position="none")
    
    r_1kb <- ggplot(data=m1kb, aes(x=(bin -1) * 1e+3, y=avg_rec)) + 
      geom_line(data=m1kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_rec), max(m1kb$avg_rec)),
                         labels=scientific) +
      labs(title=NULL, x="Position", y="r") +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_text(size=12),
            axis.text.y=element_text(size=12),
            axis.title.y=element_text(size=16),
            plot.title=element_text(size=20),
            legend.position="none")
    
    lands_1kb <- plot_grid(pi_1kb, u_1kb, B_1kb, r_1kb, align='v', ncol=1)

    pi_10kb <- ggplot(data=m10kb, aes(x=(bin -1) * 1e+4, y=avg_pi)) +
      geom_line(data=m10kb) + theme_bw() + 
      scale_y_continuous(breaks=pretty_breaks(),
                         #limits=c(min(m1kb$avg_pi), max(m1kb$avg_pi)),
                         labels=scale.4d) +
      labs(title="10 kb", x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position = "none") 
    
    u_10kb <- ggplot(data=m10kb, aes(x=(bin -1) * 1e+4, y=avg_mut)) + 
      geom_line(data=m10kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_mut), max(m1kb$avg_mut)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    B_10kb <- ggplot(data=m10kb, aes(x=(bin -1) * 1e+4, y=B)) + 
      geom_line(data=m10kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$B), max(m1kb$B)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    r_10kb <- ggplot(data=m10kb, aes(x=(bin -1) * 1e+4, y=avg_rec)) +
      geom_line(data=m10kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(),
                         #limits=c(min(m1kb$avg_rec), max(m1kb$avg_rec)),
                         labels=scientific) +
      labs(title=NULL, x="Position", y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_text(size=12),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20), legend.position="none")
    
    lands_10kb <- plot_grid(pi_10kb, u_10kb, B_10kb, r_10kb, align='v', ncol=1)

    pi_100kb <- ggplot(data=m100kb, aes(x=(bin -1) * 1e+5, y=avg_pi))+
      geom_line(data=m100kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_pi), max(m1kb$avg_pi)),
                         labels=scale.4d) +
      labs(title="100 kb", x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none") 
    
    u_100kb <- ggplot(data=m100kb, aes(x=(bin -1) * 1e+5, y=avg_mut))+
      geom_line(data=m100kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_mut), max(m1kb$avg_mut)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    B_100kb <- ggplot(data=m100kb, aes(x=(bin -1) * 1e+5, y=B))+
      geom_line(data=m100kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(),
                         #limits=c(min(m1kb$B), max(m1kb$B)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    r_100kb <- ggplot(data=m100kb, aes(x=(bin -1) * 1e+5, y=avg_rec)) +
      geom_line(data=m100kb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_rec), max(m1kb$avg_rec)),
                         labels=scientific) +
      labs(title=NULL, x="Position", y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_text(size=12),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    lands_100kb <- plot_grid(pi_100kb, u_100kb, B_100kb, r_100kb, align='v', ncol=1)
    
    pi_1Mb <- ggplot(data=m1Mb, aes(x=(bin -1) * 1e+6, y=avg_pi))+
      geom_line(data=m1Mb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(),
                         #limits=c(min(m1kb$avg_pi), max(m1kb$avg_pi)),
                         labels=scale.4d) +
      labs(title="1 Mb", x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none") 
    
    u_1Mb <- ggplot(data=m1Mb, aes(x=(bin -1) * 1e+6, y=avg_mut))+
      geom_line(data=m1Mb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         ##limits=c(min(m1kb$avg_mut), max(m1kb$avg_mut)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    B_1Mb <- ggplot(data=m1Mb, aes(x=(bin -1) * 1e+6, y=B))+
      geom_line(data=m1Mb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(),
                         #limits=c(min(m1kb$B), max(m1kb$B)),
                         labels=scientific) +
      labs(title=NULL, x=NULL, y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    r_1Mb <- ggplot(data=m1Mb, aes(x=(bin -1) * 1e+6, y=avg_rec)) +
      geom_line(data=m1Mb) + theme_bw() +
      scale_y_continuous(breaks=pretty_breaks(), 
                         #limits=c(min(m1kb$avg_rec), max(m1kb$avg_rec)),
                         labels=scientific) +
      labs(title=NULL, x="Position", y=NULL) +
      theme(axis.title.x=element_text(size=16),
            axis.text.x=element_text(size=12),
            axis.text.y=element_blank(),
            plot.title=element_text(size=20),
            legend.position="none")
    
    lands_1Mb <- plot_grid(pi_1Mb, u_1Mb, B_1Mb, r_1Mb, align='v', ncol=1)

    lands_scales <- plot_grid(lands_1kb, lands_10kb, lands_100kb, lands_1Mb, nrow=1)
    save_plot(paste("model_", i, "/rep_", j, "/maps.png", sep=""),
              lands_scales, base_height=12, base_width=24)
  }
}

# visualization of R^2 across models
r2_tbl <- data.table()
pb <- txtProgressBar(min=1, max=num_models, style=3)
for(i in 1:num_models) {
  
  setTxtProgressBar(pb, i)
  
  # converts num_rep R^2 tables of dim (3 x 4: 1kb, 10kb, 100kb x Total, u, B)
  # into 4 tables of dimension num_reps x 3 (Total, u, B)
  r2_1kb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  r2_10kb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  r2_100kb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  r2_1Mb <- as.data.frame(matrix(nrow=num_reps, ncol=4))
  
  for(j in 1:num_reps) {
    tmp <- fread(paste("model_", i, "/rep_", j, "/r2_tbl.csv", sep=""))
    
    r2_1kb[j,] <- tmp[1,]
    r2_10kb[j,] <- tmp[2,]
    r2_100kb[j,] <- tmp[3,]
    r2_1Mb[j,] <- tmp[4,]
  }
  
  tbl <- rbind.data.frame(r2_1kb, r2_10kb, r2_100kb, r2_1Mb)
  names(tbl) <- c("Total", "u", "B", "scale")
  tbl$model <- i
  tbl$rep <- rep(1:10, 4)

  r2_tbl <- rbind.data.frame(r2_tbl, tbl)
}
close(pb)

r2s <- r2_tbl %>% group_by(model, scale) %>% 
                  summarize_at(vars(Total, u, B), 
                               list(avg=mean, sd=sd))

fwrite(r2s, "r2_tbl_models.csv")

for(i in 1:num_models) {
  
  molten_avgs <- pivot_longer(r2s, cols=ends_with("avg"), names_to="variable")
  p <- ggplot(data=filter(molten_avgs, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "Total", "u")) +
    scale_x_continuous(breaks=unique(molten_avgs$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(Mean over replicates)"),
         x="Map Scale (kb)", y="Variance Explained (%)") +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16),
          legend.position="bottom")
  
  molten_sds <- pivot_longer(r2s, cols=ends_with("sd"), names_to="variable")
  q <- ggplot(data=filter(molten_sds, model==i), 
              aes(x=scale/1e+3, y=value, shape=variable)) +
    geom_line() + theme_bw() + geom_point(size=4) +
    scale_shape_manual(values=c(0, 1, 8),
                       name=NULL, labels=c("B", "Total", "u")) +
    scale_x_continuous(breaks=unique(molten_sds$scale/1e+3), trans="log10") +
    scale_y_continuous(breaks=pretty_breaks()) +
    labs(title=paste("Model", i, "(SD over replicates)"),
         x="Map Scale (kb)", y=NULL) +
    theme(axis.title=element_text(size=16), 
          axis.text=element_text(size=12), 
          axis.text.x=element_text(size=12),
          legend.text=element_text(size=16), 
          legend.position="bottom")
  
  save_plot(paste("model_", i, "_r2.png", sep=""), plot_grid(p, q, nrow=1), 
            base_height=10, base_width=15)
}

# we simplify plots a little
r2s_f <- dplyr::select(r2s, -starts_with("Total")) %>%
         dplyr::select(., -ends_with("sd"))
models_f <- dplyr::select(models, c(num_exons,
                                    avg_mut_spans,
                                    avg_rec_spans,
                                    shapes_rate_u,
                                    shapes_rate_r, 
                                    model))
r2_models <- merge(models_f, r2s_f, by="model")
m_r2_models <- pivot_longer(r2_models, cols=ends_with("avg"), names_to="var")

p1 <- ggplot(data=filter(m_r2_models, num_exons==600, shapes_rate_r==1, avg_rec_spans==1e+3),
       aes(x=scale/1e+3, y=value, shape=var)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u"))+
  scale_color_discrete(name="shape rec. dist.", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("Mean", expression(R^2),
                   "over replicates, cols->shape(u), rows->avg mut. span"),
       x="Map Scale (kb)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

p2 <- ggplot(data=filter(m_r2_models, num_exons==1500),
             aes(x=scale/1e+3, y=value, color=as.factor(shapes_rate_r), shape=var)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u"))+
  scale_color_discrete(name="shape rec. dist.", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("Mean", expression(R^2),
                   "over replicates, cols->shape(u), rows->avg mut. span"),
       x="Map Scale (kb)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

p3 <- ggplot(data=filter(m_r2_models, num_exons==3000),
             aes(x=scale/1e+3, y=value, color=as.factor(shapes_rate_r), shape=var)) +
  geom_line() + geom_point(size=4) + theme_bw() + 
  facet_grid(+avg_mut_spans~shapes_rate_u) +
  scale_shape_manual(values=c(0, 1, 2), name=NULL, labels=c("B", "u"))+
  scale_color_discrete(name="shape rec. dist.", type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_r2_models$scale/1e+3), trans="log10") +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("Mean", expression(R^2),
                   "over replicates, cols->shape(u), rows->avg mut. span"),
       x="Map Scale (kb)", y="Variance Explained (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

cp <- plot_grid(p1, p2, p3, align='v', ncol=1)
save_plot("r2_plot_clean.png", cp, dpi=500)

q <- ggplot(data=filter(m_r2_models, var=="u_avg"),
            aes(x=shapes_rate_u, y=value, color=as.factor(shapes_rate_r),
                shape=as.factor(avg_mut_spans/1e+3))) +
  geom_line() + geom_point(size=4) + theme_bw() + facet_wrap(~scale/1e+3) +
  scale_shape_manual(values=c(0, 1, 2), name="Avg. Mut. Span (kb)") +
  scale_color_discrete(name=expression(alpha), type=c("plum3", "seagreen3")) +
  scale_x_continuous(breaks=unique(m_r2_models$shapes_rate_u)) +
  scale_y_continuous(breaks=pretty_breaks()) +
  labs(title=paste("Mean", expression(R^2),
                   "over replicates, cols->genomic scale (kb)"),
       x="Shape of mutation rate distribution",
       y="Variance Explained by Mutation (%)") +
  theme(axis.title=element_text(size=16), 
        axis.text=element_text(size=12), 
        axis.text.x=element_text(size=12),
        legend.text=element_text(size=16),
        legend.title=element_text(size=16),
        legend.position="bottom")

save_plot("r2_u_only.png", q, base_height=8, base_width=16)

# meta linear models
## 1 kb
std_r2_1kb <- as.data.frame(r2_models %>% filter(., scale==1e+3) %>% 
                            apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_1kb <- lm(u_avg ~ (shapes_rate_u + shapes_rate_r + avg_mut_spans)^2,
              data=std_r2_1kb)
m_B_1kb <- lm(B_avg ~ (shapes_rate_u + shapes_rate_r + avg_mut_spans)^2,
              data=std_r2_1kb)

summary(m_u_1kb)
summary(m_B_1kb)

## 10 kb
std_r2_10kb <- as.data.frame(r2_models %>% filter(., scale==1e+4) %>% 
                               apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_10kb <- lm(u_avg ~ (shapes_rate_u + shapes_rate_r + avg_mut_spans)^2,
               data=std_r2_10kb)
m_B_10kb <- lm(B_avg ~ (shapes_rate_u + shapes_rate_r + avg_mut_spans)^2,
               data=std_r2_10kb)

summary(m_u_10kb)
summary(m_B_10kb)

## 100 kb
std_r2_100kb <- as.data.frame(r2_models %>% filter(., scale==1e+5) %>% 
                              apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_100kb <- lm(u_avg ~ (shapes_rate_u + shapes_rate_r + avg_mut_spans)^2,
                data=std_r2_100kb)
m_B_100kb <- lm(B_avg ~ (shapes_rate_u + shapes_rate_r + avg_mut_spans)^2,
                data=std_r2_100kb)

summary(m_u_100kb)
summary(m_B_100kb)


meta_lm_u <- rbind.data.frame(m_u_1kb$coefficients,
                              m_u_10kb$coefficients,
                              m_u_100kb$coefficients)
names(meta_lm_u) <- names(m_u_1kb$coefficients)

meta_lm_B <- rbind.data.frame(m_B_1kb$coefficients,
                              m_B_10kb$coefficients,
                              m_B_100kb$coefficients)
names(meta_lm_B) <- names(m_B_1kb$coefficients)

## 1 Mb
std_r2_1Mb <- as.data.frame(r2_models %>% filter(., scale==1e+5) %>% 
                            apply(., 2, function(x) (x-mean(x)) / sd(x)))

m_u_1Mb <- lm(u_avg ~ (shapes_rate_u + shapes_rate_r + avg_mut_spans)^2,
              data=std_r2_1Mb)
m_B_1Mb <- lm(B_avg ~ (shapes_rate_u + shapes_rate_r + avg_mut_spans)^2,
              data=std_r2_1Mb)

summary(m_u_1Mb)
summary(m_B_1Mb)


meta_lm_u <- rbind.data.frame(m_u_1kb$coefficients,
                              m_u_10kb$coefficients,
                              m_u_1Mb$coefficients)
names(meta_lm_u) <- names(m_u_1kb$coefficients)

meta_lm_B <- rbind.data.frame(m_B_1kb$coefficients,
                              m_B_10kb$coefficients,
                              m_B_1Mb$coefficients)
names(meta_lm_B) <- names(m_B_1kb$coefficients)

meta_lm_u$bin_size <- c(1e+3, 1e+4, 1e+5)
meta_lm_B$bin_size <- c(1e+3, 1e+4, 1e+5)

fwrite(select(meta_lm_u, c(scale_sel, 
                           shapes_rate_u,
                           shapes_rate_r,
                           `scale_sel:shapes_rate_u`,
                           `scale_sel:shapes_rate_r`,
                           `shapes_rate_u:shapes_rate_r`)), "meta_lm_u.csv")
fwrite(select(meta_lm_B, c(scale_sel, 
                           shapes_rate_u,
                           shapes_rate_r,
                           `scale_sel:shapes_rate_u`,
                           `scale_sel:shapes_rate_r`,
                           `shapes_rate_u:shapes_rate_r`)), "meta_lm_B.csv")

#interact_plot(m_u_1kb, pred=scale_sel, modx=shapes_rate_r)
#interact_plot(m_u_1kb, pred=shapes_rate_u, modx=shapes_rate_r)
#interact_plot(m_u_1kb, pred=scale_sel, modx=shapes_rate_u)

cat("bgs_viz.R is done!\n")
