#!/usr/bin/env Rscript
args=commandArgs(trailingOnly=T)

m <- as.numeric(args[1]) # index of focal model

suppressMessages({
  library(R.utils)
  library(tidyverse)
  library(MASS)
  library(lmtest)
  library(nlme)
  library(car)
  library(scales)
  library(data.table)
  library(interactions)
  library(GenomicRanges)
})


# loads the main tables generated by setup_models_2.Rmd
models <- fread("../../models.csv")
cat(paste("Building random genomic landscapes under model", m, "\n"))

L <- models$L[m]
mut_spans_large <- models$mut_spans_large[m]
mut_spans_small <- models$mut_spans_small[m]
shape_rate_u_large <- models$shape_rate_u_large[m]
shape_rate_u_small <- models$shape_rate_u_small[m]
  
# large scale, low variance
mut_spans_large <- rep(mut_spans_large, L/mut_spans_large)
mmap_large <- suppressMessages(setDT(bind_cols(chr="chr1",
    dplyr::lag(cumsum(mut_spans_large), n=1, default=0),
    dplyr::lag(cumsum(mut_spans_large), n=0, default=0))))  
names(mmap_large) <- c("chr", "start", "end")
mmap_large$start <- 1 + mmap_large$start
mmap_large$uf <- rgamma(n=length(mut_spans_large), 
                        shape=shape_rate_u_large, 
                        rate=shape_rate_u_large)

# small scale, high variance
mut_spans_small <- rep(mut_spans_small, L/mut_spans_small)
mmap_small <- suppressMessages(setDT(bind_cols(chr="chr1",
    dplyr::lag(cumsum(mut_spans_small), n=1, default=0),
    dplyr::lag(cumsum(mut_spans_small), n=0, default=0))))  
names(mmap_small) <- c("chr", "start", "end")
mmap_small$start <- 1 + mmap_small$start
mmap_small$uf <- rgamma(n=length(mut_spans_small),
                        shape=shape_rate_u_small, 
                        rate=shape_rate_u_small)

gr_small <- makeGRangesFromDataFrame(mmap_small, keep.extra.columns=T)
gr_large <- makeGRangesFromDataFrame(mmap_large, keep.extra.columns=T)

hits <- findOverlaps(query=gr_small, subject=gr_large) 
hit_list <- as.data.frame(hits)
names(hit_list) <- c("small_bin", "large_bin")

mmap_small$large_bin <- subjectHits(hits)
mmap_large$large_bin <- 1:nrow(mmap_large)
tbl <- merge(mmap_small, mmap_large, by="large_bin")
mmap_small$u <- tbl$uf.x * tbl$uf.y * 1e-8
mmap <- dplyr::select(mmap_small, -c(uf, large_bin))

# binning
bin_size <- 1e+3
bins <- rep(bin_size, floor(L / bin_size))
bins <- suppressMessages(bind_cols(chr="chr1",
         dplyr::lag(cumsum(bins), n=1, default=1),
         dplyr::lag(cumsum(bins), n=0, default=0)))
names(bins) <- c("chr", "start", "end")
gr_bins <- makeGRangesFromDataFrame(bins)

mut_gr <- makeGRangesFromDataFrame(mmap, keep.extra.columns=T)
hits <- findOverlaps(query=gr_bins, subject=mut_gr) 
hit_list <- as.data.frame(hits)
names(hit_list) <- c("bin_1kb", "mut_bins")
mmap$mut_bins <- 1:nrow(mmap)
mmap_1kb <- merge(mmap, hit_list) %>% group_by(bin_1kb) %>%
  mutate(avg_mut=weighted.mean(u, end-start))
mmap_1kb <- mmap_1kb %>% distinct(bin_1kb, .keep_all=T) 
mmap_1kb$start <- bins$start
mmap_1kb$end <- bins$end

mmap_1kb$bin_10kb <- (mmap_1kb$bin_1kb - 1) %/% 10
mmap_1kb$bin_100kb <- (mmap_1kb$bin_1kb - 1) %/% 100
mmap_1kb$bin_1Mb <- (mmap_1kb$bin_1kb - 1) %/% 1000

mmap_10kb <- mmap_1kb %>% group_by(bin_10kb) %>% summarise_at("avg_mut", mean)
mmap_100kb <- mmap_1kb %>% group_by(bin_100kb) %>% summarise_at("avg_mut", mean)
mmap_1Mb <- mmap_1kb %>% group_by(bin_1Mb) %>% summarise_at("avg_mut", mean)

bins_1kb <- rep(1e+3, floor(L / 1e+3))
bins_1kb <- suppressMessages(bind_cols(chr="chr1",
               dplyr::lag(cumsum(bins_1kb), n=1, default=0),
               dplyr::lag(cumsum(bins_1kb), n=0, default=0)))
names(bins_1kb) <- c("chr", "start", "end")
bins_1kb$avg_mut <- mmap_1kb$avg_mut
  
bins_10kb <- rep(1e+4, floor(L / 1e+4))
bins_10kb <- suppressMessages(bind_cols(chr="chr1",
               dplyr::lag(cumsum(bins_10kb), n=1, default=0),
               dplyr::lag(cumsum(bins_10kb), n=0, default=0)))
names(bins_10kb) <- c("chr", "start", "end")
bins_10kb$avg_mut <- mmap_10kb$avg_mut

bins_100kb <- rep(1e+5, floor(L / 1e+5))
bins_100kb <- suppressMessages(bind_cols(chr="chr1",
                dplyr::lag(cumsum(bins_100kb), n=1, default=0),
                dplyr::lag(cumsum(bins_100kb), n=0, default=0)))
names(bins_100kb) <- c("chr", "start", "end")
bins_100kb$avg_mut <- mmap_100kb$avg_mut

bins_1Mb <- rep(1e+6, floor(L / 1e+6))
bins_1Mb <- suppressMessages(bind_cols(chr="chr1",
              dplyr::lag(cumsum(bins_1Mb), n=1, default=0),
              dplyr::lag(cumsum(bins_1Mb), n=0, default=0)))
names(bins_1Mb) <- c("chr", "start", "end")
bins_1Mb$avg_mut <- mmap_1Mb$avg_mut

fwrite(bins_1kb, "maps_1kb.csv.gz")
fwrite(bins_10kb, "maps_10kb.csv.gz")
fwrite(bins_100kb, "maps_100kb.csv.gz")
fwrite(bins_1Mb, "maps_1Mb.csv.gz")

y <- mmap$u / mean(mmap$u)
MASS::fitdistr(y, "gamma")
MASS::fitdistr(mmap_small$uf, "gamma")

y1kb <- mmap_1kb$avg_mut / mean(mmap_1kb$avg_mut)
MASS::fitdistr(y1kb, "gamma")

y10kb <- mmap_10kb$avg_mut / mean(mmap_10kb$avg_mut)
MASS::fitdistr(y10kb, "gamma")

y100kb <- mmap_100kb$avg_mut / mean(mmap_100kb$avg_mut)
MASS::fitdistr(y100kb, "gamma")

y1Mb <- mmap_1Mb$avg_mut / mean(mmap_1Mb$avg_mut)
MASS::fitdistr(y1Mb, "gamma")
